[package]
name = "robo-trek"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { version = "0.12", default-features = false, features = [
    "builder",
    "chrono",
    "client",
    "gateway",
    "http",
    "model",
    "rustls_backend",
    "utils",
] }
tokio = { version = "1.21.2", features = ["macros", "net", "rt"] }
axum = { version = "0.7", default-features = false, features = [
    "http1",
    "json",
    "tokio",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"
dotenvy = "0.15"
envy = "0.3"
handlebars = "6.4.4"
redb = "4.1.0"
tempfile = "3.27.0"

[profile.release]
opt-level = 'z'
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[dev-dependencies]
http-body-util = "0.1.5"
tower = { version = "0.5.3", features = ["util"] }
