[target.x86_64-unknown-linux-gnu]
rustflags = [
    # Arch: `sudo pacman -S lld clang`
    # "-Clink-arg=-fuse-ld=lld",
    # Mold linker
    # Arch: sudo pacman -S mold clang
    "-Clink-arg=-fuse-ld=mold",

    # Nightly
    "-Zshare-generics=y"
]
